# Generated by Django 3.2.4 on 2021-06-26 18:49

import claims.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.CharField(max_length=200)),
                ('Vehicle_Year_Make', models.CharField(max_length=200)),
                ('Vehicle_Model', models.CharField(max_length=200)),
                ('Vehicle_No', models.CharField(max_length=200)),
                ('Date_of_accident', models.DateField()),
                ('Time_of_accident', models.TimeField()),
                ('Location', models.CharField(max_length=200)),
                ('Type_of_Loss', models.CharField(choices=[('Own Damage', 'Own Damage'), ('Knock for Knock', 'Knock for Knock'), ('Windscreen Damage', 'Windscreen Damage'), ('Theft', 'Theft')], max_length=100)),
                ('Desrciption_of_Loss', models.TextField()),
                ('Police_report_Lodged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Anybody_Injured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Photo', models.ImageField(upload_to=claims.models.get_upload_filename)),
                ('PDF_document_of_Insurance_Cover_Note', models.FileField(upload_to=claims.models.get_upload_filename)),
                ('Claim_Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Accepted', 'Accepted')], default='In Progress', max_length=20)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
