# Generated by Django 3.2.4 on 2021-06-26 10:32

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.CharField(max_length=200)),
                ('Vehicle_Year_Make', models.CharField(max_length=200)),
                ('Vehicle_Model', models.CharField(max_length=200)),
                ('Vehicle_No', models.CharField(max_length=200)),
                ('Date_and_time_of_accident', models.DateTimeField()),
                ('Location', models.CharField(max_length=200)),
                ('Type_of_Loss', models.CharField(choices=[('Own Damage', 'Own Damage'), ('Knock for Knock', 'Knock for Knock'), ('Windscreen Damage', 'Windscreen Damage'), ('Theft', 'Theft')], max_length=100)),
                ('Desrciption_of_Loss', models.TextField()),
                ('Police_report_Lodged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Anybody_Injured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Photo', models.ImageField(upload_to=claims.models.get_upload_filename)),
                ('PDF_document_of_Insurance_Cover_Note', models.FileField(upload_to=claims.models.get_upload_filename)),
                ('Claim_Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Accepted', 'Accepted')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
